version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  bot:
    build: .
    environment:
      - TOKEN_BOT=${TOKEN_BOT}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DB_PATH=/app/data/users.db
      - LOG_DIR=/app/logs
    depends_on:
      - redis
    volumes:
      - bot_data:/app/data
      - bot_logs:/app/logs
    restart: unless-stopped

  scheduler:
    build: .
    command: python scheduler.py
    environment:
      - TOKEN_BOT=${TOKEN_BOT}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DB_PATH=/app/data/users.db
      - LOG_DIR=/app/logs
    depends_on:
      - redis
      - bot
    volumes:
      - bot_data:/app/data
      - bot_logs:/app/logs
    restart: unless-stopped

volumes:
  redis_data:
  bot_data:
  bot_logs: 